script:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
    
language: node_js
node_js: 
      # Node 10.3+ includes npm@6 which has good "npm ci" command
    - 10.8
addons:
    apt:
        packages:
          - libgconf-2-4
cache:
    # cache both npm modules and Cypress binary
    directories:
        - ~/.npm
        - ~/.cache
    override:
        - npm ci
        - npm run cy:verify

env:
    global:
        - CY_KEY=6d187511-4bf6-4de2-98e4-042d4d075189
        - CI_THREAD_INDEX="/cypress/integration/Sections/*"


defaults: &defaults
  script:
    #   ## print all Travis environment variables for debugging
        - $(npm bin)/print-env TRAVIS
        - npm run start:ci &
        - npm run cy:run -- --record --key $CY_KEY --parallel --group $CI_THREAD_INDEX
        # after all tests finish running we need
        # to kill all background jobs (like "npm start &")
        - kill $(jobs -p) || true
jobs:
  include:
    # we have multiple jobs to execute using just a single stage
    # but we can pass group name via environment variable to Cypress test runner
    - stage: test
        env: 
        - CI_THREAD_INDEX="3x-chrome"
        <<: *defaults