context('ABM Agent', () => {

  it('Supervisor Successful Login', function(){
    cy.visit("https://oficina.ucontactcloud.com")
    cy.get('#cmbRol_chosen').click()
    cy.get('.active-result').contains('Supervisor').click()
    cy.get('[name="user"]').type('Integra')
    cy.get('[name="pass"]').type('1nt3gr4{enter}')
    // cy.wait(10000)
    cy.location('href').should('contain', '/views/portal')
    cy.get('#mm-blocker').click()
    cy.get('#username').should('contain', 'Integra')
    cy.saveLocalStorage()
  })

  it('Alta de Agente', function(){
    cy.restoreLocalStorage()
    cy.get('#sideBarIcon').click()
    cy.get('#dropUsers').click()
    cy.get('#agents').click()
    cy.get('#submit').click()
    cy.get('#toast-container').contains('Context is required').click()
    cy.get('#toast-container').contains('Must type a password').click()
    cy.get('#toast-container').contains('Phone can not be lower than 3 digits').click()
    cy.get('#toast-container').contains('Must type a phone').click()
    cy.get('#toast-container').contains('Must type name').click()
    cy.get('#contextoAgente_chosen > .chosen-single').click()
    cy.get('[data-option-array-index="2"]').click()
    cy.get('#nombreAgente').type('AutomationAgent')
    cy.get('#telefonoAgente').type('4070')
    cy.get('#passwordAgente').type('123456')
    cy.get('#submit').click()
    // cy.wait(6000)
    cy.get('#toast-container').contains('Action performed successfully')
    cy.get('#toast-container').click()
    cy.saveLocalStorage()
  })

  it('Modificar Agente', function(){
    cy.restoreLocalStorage()
    cy.get('#basicDataTable_filter > label > input').type('AutomationAgent')
    cy.get('.sorting_1').click()
    cy.get('#agentFullName').type('User Automated')
    cy.get('#passwordAgente').clear()
    cy.get('#submit').click()
    cy.get('#toast-container').contains('Must type a password')
    cy.get('#passwordAgente').type('123456')
    cy.get('#emailAgente').type('automation@test.com')
    cy.get('#submit').click()
    cy.saveLocalStorage()
    cy.wait(6000)
  })

  it('Agente ya existe', function(){
    cy.restoreLocalStorage()
    // cy.get('#sideBarIcon').click()
    // cy.get('#dropUsers').click()
    // cy.get('#agents').click()
    cy.get('#contextoAgente_chosen > .chosen-single').click()
    cy.get('[data-option-array-index="2"]').click()
    // cy.get('#contextoAgente').select('Agents')
    cy.get('#nombreAgente').type('AutomationAgent')
    cy.get('#telefonoAgente').type('4070')
    cy.get('#passwordAgente').type('123456')
    cy.get('#submit').click()
    cy.get('#toast-container').contains('Cant be created, already exist')    
    cy.saveLocalStorage()
  })

  it('Baja de Agente', function(){
    cy.restoreLocalStorage()
    cy.get('#basicDataTable_filter > label > input').clear().type('AutomationAgent')
    cy.get('.sorting_1').click()
    cy.get('.btn-danger').click()
    cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
    cy.get('#btnLogOut').click({force: true})
  })
  
}) 