context('Channels ABM', () => {

    it('Supervisor Successful Login', function(){
        cy.visit("https://203.ucontactcloud.com")
        cy.get('#cmbRol_chosen').click()
        cy.get('.active-result').contains('Supervisor').click()
        cy.get('[name="user"]').type('Integra')
        cy.get('[name="pass"]').type('1nt3gr4{enter}')
        cy.location('href').should('contain', '/views/portal')
        cy.get('#mm-blocker').click()
        cy.get('#username').should('contain', 'Integra')
        cy.saveLocalStorage()
    })

    it('Alta Webchat', function(){
        cy.restoreLocalStorage()
        cy.get('#sideBarIcon').click()
        cy.get('#navigation > .menu > li:nth-child(2)').click()
        cy.get('#webchatcampaigns').click()
            cy.get('#guardarCampWebChat').click()
                cy.get('.toast').contains('Must type name').click()
                cy.get('#nombreCampWebChat').type('AutomatedChannel')
            cy.get('#guardarCampWebChat').click()
                cy.get('.toast').contains('Must choose strategy').click()
                cy.get('#estrategiaCampWebChat_chosen').click()
                cy.get('.chosen-results').find('[data-option-array-index="7"]').click()
            cy.get('#guardarCampWebChat').click()
                cy.get('.toast').contains('Type service level')
                cy.get('#nivelServicioCampWebChat').type('10')
            cy.get('#guardarCampWebChat').click()
            cy.get('.toast-success').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('Baja Webchat', function(){
        cy.restoreLocalStorage()
        cy.get('#tablaCampanas_filter > label > input').type('AutomatedChannel')
            cy.get('.sorting_1').click()
            cy.get('#borrarCampWebChat').click()
            cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
            cy.get('.toast-success').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })
    
    it('Alta HeyNow', function(){
        cy.restoreLocalStorage()
        cy.get('#sideBarIcon').click()
        cy.get('#navigation > .menu > li:nth-child(2)').click()
        cy.get('#whatsappcampaigns').click({force:true})
        cy.get('#guardarCampWhatsapp').click()
                cy.get('.toast').contains('Must type name').click()
                cy.get('#nombreCampWhatsapp').type('AutomatedChannel')
            cy.get('#guardarCampWhatsapp').click()
                cy.get('.toast').contains('Must choose strategy').click()
                cy.get('#estrategiaCampWhatsapp_chosen').click()
                cy.get('.chosen-results').find('[data-option-array-index="7"]').click()
            cy.get('#guardarCampWhatsapp').click()
                cy.get('.toast').contains('Type service level')
                cy.get('#nivelServicioCampWhatsapp').type('10')
            cy.get('#guardarCampWhatsapp').click()
            cy.get('.toast-success').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('Baja HeyNow', function(){
        cy.restoreLocalStorage()
        cy.get('#tablaCampanas_filter > label > input').clear().type('AutomatedChannel')
            cy.get('.sorting_1').click()
            cy.get('#borrarCampWhatsapp').click()
            cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
            cy.get('.toast-success').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('Alta SMS', function(){
        cy.restoreLocalStorage()
        cy.get('#sideBarIcon').click()
        cy.get('#navigation > .menu > li:nth-child(2)').click()
        cy.get('#smscampaigns').click({force:true})
        cy.get('#guardar').click({force:true})
                cy.get('.toast').contains('Check fields').click()
                cy.get('#nombre').type('AutomatedChannel')
                cy.get('#smsProviders_chosen').click()
                cy.get('.chosen-results').find('[data-option-array-index="2"]').click() //Esto debe ser optimizado en algun momento ya que esta hardcodeado//
                cy.get('#estrategia_chosen').click()
                cy.get('.chosen-results').find('[data-option-array-index="7"]').click()
                cy.get('#nivelServicio').type('10')
                cy.get('#didports').type('web')
            cy.get('#guardar').click()
            cy.get('.toast').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('Baja SMS', function(){
        cy.restoreLocalStorage()
        cy.get('#tablaCampanas_filter > label > input').clear().type('AutomatedChannel')
            cy.get('.sorting_1').click()
            cy.get('#borrar').click()
            cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
            cy.get('.toast').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('Alta Email', function(){
        cy.restoreLocalStorage()
        cy.get('#sideBarIcon').click()
        cy.get('#navigation > .menu > li:nth-child(2)').click()
        cy.get('#emailcampaigns').click({force:true})
        cy.get('#guardarEmail').click()
                cy.get('.toast').contains('Campaign name allows characters A-Z, 0-9, _ , - ').click()
                cy.get('.toast').contains('Type service level').click()
                cy.get('.toast').contains('Must choose strategy').click()
            cy.get('#guardarEmail').click()
                cy.get('.toast').contains('Must type an email').click()
                cy.get('.toast').contains('Must type a password').click()
                cy.get('.toast').contains('Must type SMTP ip and port').click()
                cy.get('.toast').contains('You must provide host and port IMAP or POP').click()
                cy.get('#nombreEmail').type('AutomatedChannel')
                cy.get('#nivelServicioEmail').type('10')
                cy.get('#estrategiaEmail_chosen').click()
                cy.get('.chosen-results').find('[data-option-array-index="7"]').click()
                cy.get('#accountEmail').type('automationtestintegra@gmail.com')
                cy.get('#passwordEmail').type('1nt3gr4!')
                cy.get('#outbondSMTPEmail').type('smtp.gmail.com')
                cy.get('#smtpEmailPort').type('587')
                cy.get('#inboundINAPEmail').type('imap.gmail.com')
                cy.get('#imapEmailPort').type('993')
                cy.get('#inboundPOPEmail').type('pop.gmail.com')
                cy.get('#popEmailPort').type('995')
            cy.get('#guardarEmail').click()
            cy.wait(6000)
            cy.get('.toast').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('Baja Email', function(){
        cy.restoreLocalStorage()
        cy.get('#tablaCampanasEmail_filter > label > input').clear().type('AutomatedChannel')
            cy.get('.sorting_1').click()
            cy.get('#borrarEmail').click()
            cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
            cy.get('.toast').contains('Action performed successfully')
            cy.get('#btnLogOut').click()
        cy.saveLocalStorage()
    })

})