context('Campaign ABM', () => {

    it('Supervisor Successful Login', function(){
        cy.visit("https://oficina.ucontactcloud.com")
        cy.get('#cmbRol_chosen').click()
        cy.get('.active-result').contains('Supervisor').click()
        cy.get('[name="user"]').type('Integra')
        cy.get('[name="pass"]').type('1nt3gr4{enter}')
        cy.location('href').should('contain', '/views/portal')
        cy.get('#mm-blocker').click()
        cy.get('#username').should('contain', 'Integra')
        cy.saveLocalStorage()
    })  

    it('Alta de Campaign Inbound', function(){
        cy.restoreLocalStorage()
        cy.get('#sideBarIcon').click()
        cy.get('#navigation > .menu > li:nth-child(2)').click()
        cy.get('#campaigns').click()
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('DID format is not correct, please check the field and try again')
        cy.get('#toast-container').contains('Must type DID')
        cy.get('#toast-container').contains('Campaign name allows characters A-Z, 0-9, _ , - ')
        cy.get('#nombre').type('AutomationVICampaign')
        cy.get('#did').type('2987654')
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('Alta de Campaign Outbound', function(){
        cy.restoreLocalStorage()
        cy.get('#vaciarCampos').click()
        cy.get(':nth-child(2) > .radio > label').click()
        cy.get('#nombre').type('Automation/#Campaign')
        cy.get('#did').type('543216789')
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('Campaign name allows characters A-Z, 0-9, _ , - ').click()
        cy.get('#nombre').clear()
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('Campaign name allows characters A-Z, 0-9, _ , - ').click()
        cy.get('#nombre').type('AutomationVOCampaign')
        cy.get('#guardar').click()
        cy.wait(3000)
        cy.get('.toast').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('Modificar Campaign', function(){
        cy.restoreLocalStorage()
        cy.get('#tablaCampanas_filter > label > input').type('AutomationVICampaign')
        cy.get('.sorting_1').contains('Automation').click()
        cy.get('#did').clear()
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('DID format is not correct, please check the field and try again').click()
        cy.get('#toast-container').contains('Must type DID').click()
        cy.get('#email').type('automation@test.com')
        cy.get('#did').type('2456789')
        cy.get('#guardar').click()
        cy.wait(3000)
        cy.get('#toast-container').contains('Action performed successfully').click()       
        cy.saveLocalStorage() 
    })

    it('Campaign ya existe', function(){
        cy.restoreLocalStorage()
        cy.get('#vaciarCampos').click()
        cy.get('#nombre').type('AutomationVICampaign')
        cy.get('#did').type('2987654')
        cy.get('#guardar').click()
        cy.get('.toast-message').contains('Action performed wrong').click()
        cy.saveLocalStorage()
    })

    it('Baja de Campaigns', function(){
        cy.restoreLocalStorage()
        cy.get('#tablaCampanas_filter > label > input').clear()
        cy.get('#tablaCampanas_filter > label > input').type('Automation')
        cy.get('.sorting_1').contains('VI').click()
        cy.get('#borrar').click()
        cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
        cy.get('#toast-container').contains('Action performed successfully').click()
        cy.get('.sorting_1').contains('VO').click()
        cy.get('#borrar').click()
        cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
        cy.get('#toast-container').contains('Action performed successfully')
        cy.saveLocalStorage()
    })

    it('1st Alta Agent-Camp, Asigna', function(){
        cy.restoreLocalStorage()
        cy.get('#dropUsers').click()
        cy.get('#agents').click()
            cy.get('#contextoAgente').select('Agents')
            cy.get('#nombreAgente').type('AutomationAgent')
            cy.get('#telefonoAgente').type('4070')
            cy.get('#passwordAgente').type('123456')
            cy.get('#submit').click()
            cy.wait(6000)
        cy.get('#navigation > .menu > li:nth-child(2)').click()
        cy.get('#campaigns').click()
            cy.get('#nombre').type('AutomationCampaign')
            cy.get('#did').type('2987654')
            cy.get('#guardar').click()
        cy.get('#tabVoiceMembers-tab').click()
        cy.wait(6000)
        cy.get('#tablaCampanasVoiceMemb_filter > label > input').type('Automation')
        cy.get('#tablaCampanasVoiceMembBody > .gradeA > .sorting_1').click()
        cy.get('#tablaAgentesVoiceCamp_filter > label > input').type('Automation')
            cy.get('#agente_4070 > .sorting_1').click()
            cy.get('#btnAgregarVoiceMemb').click()
            cy.get('#toast-container').contains('Action performed successfully')
        cy.get('.engranaje').click()
            cy.get('#modalPenalizacion').clear().type('50')
            cy.get('#aceptar').click()
    cy.saveLocalStorage()
    })

    it('2nd Baja Camp-Agent -to agile-',function(){
        cy.restoreLocalStorage()
        cy.get('#tabVoiceCampaigns-tab').click()
        cy.wait(4000)
        cy.get('#tablaCampanas_filter > label > input').clear()
        cy.get('#tablaCampanas_filter > label > input').type('Automation')
            cy.get('.sorting_1').contains('Auto').click()
            cy.get('#borrar').click()
            cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
        cy.get('#dropUsers').click({force: true})
        cy.get('#agents').click({force: true})
        cy.get('#basicDataTable_filter > label > input').type('AutomationAgent')
            cy.get('.sorting_1').click()
            cy.get('.btn-danger').click()
            cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
            cy.wait(6000)
        cy.get('#btnLogOut').click()
    })
})