context('Dialers ABM', () => {

    it('Supervisor Successful Login', function(){
        cy.visit("https://203.ucontactcloud.com")
        cy.get('#cmbRol_chosen').click()
        cy.get('.active-result').contains('Supervisor').click()
        cy.get('[name="user"]').type('Integra')
        cy.get('[name="pass"]').type('1nt3gr4{enter}')
        cy.wait(10000)
        cy.location('href').should('contain', '/views/portal')
        cy.get('#mm-blocker').click()
        cy.get('#username').should('contain', 'Integra')
        cy.saveLocalStorage()
    })

    it('Alta PowerDialer', function(){
        cy.restoreLocalStorage()
        cy.get('#sideBarIcon').click()
        cy.get('#navigation > .menu > li:nth-child(5)').click()
        cy.get('#dialers').click()
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('Must type Caller ID').click()
        cy.get('#toast-container').contains('Must type dial string').click()
        cy.get('#toast-container').contains('Must choose dialer type').click()
        cy.get('#tipoDiscador_chosen').click()
        cy.get('.active-result').contains('PowerDialer').click()
        cy.get('#nombreCampanaText').type('AutomationDialerPD')
        cy.get('#cadenaMarcado').type('SIP/uContact/')
        cy.get('#callerId').type('2345678')
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('Dialer and campaign created , do not forget to add agents').click()
        cy.saveLocalStorage()
    })

    it('AB Predictive', function (){
        cy.restoreLocalStorage()
        cy.get('#tipoDiscador_chosen').click()
        cy.get('.active-result').contains('Predictive').click()
        cy.get('#nombreCampanaText').type('AutomationDialerPT')
        cy.get('#cadenaMarcado').type('SIP/uContact/')
        cy.get('#callerId').type('2345678')
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('Dialer and campaign created , do not forget to add agents').click()
        cy.wait(3000)
        cy.get('#tablaDiscadores_filter > label > input').type('Auto')
        cy.get('.sorting_1').contains('Predictive').click()
        cy.get('#eliminar').click()
        cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
        cy.get('#toast-container').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('AB Progressive', function (){
        cy.restoreLocalStorage()
        cy.get('#tipoDiscador_chosen').click()
        cy.get('.active-result').contains('Progressive').click()
        cy.get('#nombreCampanaText').type('AutomationDialerPG')
        cy.get('#cadenaMarcado').type('SIP/uContact/')
        cy.get('#callerId').type('2345678')
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('Dialer and campaign created , do not forget to add agents').click()
        cy.wait(4000)
        cy.get('#tablaDiscadores_filter > label > input').clear().type('PG')
        cy.get('.sorting_1').contains('Progressive').click()
        cy.get('#eliminar').click()
        cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
        cy.get('#toast-container').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('AB Preview', function (){
        cy.restoreLocalStorage()
        cy.get('#tipoDiscador_chosen').click()
        cy.get('.active-result').contains('Preview').click()
        cy.get('#nombreCampanaText').type('AutomationDialerPV')
        cy.get('#cadenaMarcado').type('SIP/uContact/')
        cy.get('#callerId').type('2345678')
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('Dialer and campaign created , do not forget to add agents').click()
        cy.wait(3000)
        cy.get('#tablaDiscadores_filter > label > input').clear().type('Auto')
        cy.get('.sorting_1').contains('Preview').click()
        cy.get('#eliminar').click()
        cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
        cy.get('#toast-container').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('AB VoiceBroadCast', function (){
        cy.restoreLocalStorage()
        cy.get('#tipoDiscador_chosen').click()
        cy.get('.active-result').contains('VoiceBroadCast').click()
        cy.get('#nombreCampanaText').type('AutomationDialerVBC')
        cy.get('#cadenaMarcado').type('SIP/uContact/')
        cy.get('#callerId').type('2345678')
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('Dialer and campaign created , do not forget to add agents').click()
        cy.get('#tablaDiscadores_filter > label > input').clear().type('Auto')
        cy.get('.sorting_1').contains('VoiceBroadCast').click()
        cy.get('#eliminar').click()
        cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
        cy.get('#toast-container').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('Modificar PowerDialer', function(){
        cy.restoreLocalStorage()
        cy.get('#tablaDiscadores_filter > label > input').clear().type('Auto')
        cy.get('.sorting_1').contains('Power').click()
        cy.get('#cadenaMarcado').clear()
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('Must type dial string').click()
        cy.get('#cadenaMarcado').type('SIP/CARRIER/')
        cy.get('#callerId').clear()
        cy.wait(3000)
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('Must type Caller ID').click()
        cy.get('#callerId').clear().type('2876345')
        cy.get('#formulario > :nth-child(1) > :nth-child(3)').click()
        cy.wait(3000)
        cy.get('#guardar').click()
        cy.get('#toast-container').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('Baja PowerDialer', function(){
        cy.restoreLocalStorage()
        cy.get('#tablaDiscadores_filter > label > input').clear().type('Auto')
        cy.get('.sorting_1').contains('Power').click()
        cy.get('#eliminar').click()
        cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
        cy.get('#toast-container').contains('Action performed successfully').click()
        cy.saveLocalStorage()
    })

    it('1st Alta Agent-Dialer', function(){
        cy.restoreLocalStorage()
        cy.get('#dropUsers').click()
        cy.get('#agents').click()
            cy.get('#contextoAgente').select('Agents')
            cy.get('#nombreAgente').type('AutomationAgent')
            cy.get('#telefonoAgente').type('4070')
            cy.get('#passwordAgente').type('123456')
            cy.get('#submit').click()
        cy.wait(6000)
        cy.get('#navigation > .menu > li:nth-child(5)').click()
        cy.get('#dialers').click()
            cy.get('#tipoDiscador_chosen').click()
            cy.get('.active-result').contains('PowerDialer').click()
            cy.get('#nombreCampanaText').type('AutomationDialerPD')
            cy.get('#cadenaMarcado').type('SIP/uContact/')
            cy.get('#callerId').type('2345678')
            cy.get('#guardar').click()
        cy.saveLocalStorage()
        
    })

    it('2nd Asigna Agent-Dialer -to agile-', function(){
        cy.restoreLocalStorage()
        cy.get('#navigation > .menu > li:nth-child(2)').click()
        cy.get('#campaigns').click()
        cy.wait(4000)
            cy.get('#tabVoiceMembers-tab').click()
            cy.wait(4000)
            cy.get('#tablaCampanasVoiceMemb_filter > label > input').type('Automation')
            cy.get('#tablaCampanasVoiceMembBody > .gradeA > .sorting_1').click()
            cy.get('#tablaAgentesVoiceCamp_filter > label > input').type('Automation')
            cy.get('#agente_4070 > .sorting_1').click()
                cy.get('#btnAgregarVoiceMemb').click()
                cy.get('#toast-container').contains('Action performed successfully')
                cy.get('.engranaje').click()
                cy.get('#modalPenalizacion').clear().type('50')
                cy.get('#aceptar').click()
        cy.saveLocalStorage()
    })

    it('3rd Baja Dialer-Agent -to agile-', function(){
        cy.restoreLocalStorage()
        cy.get('#navigation > .menu > li:nth-child(5)').click()
        cy.get('#dialers').click()
        cy.wait(4000)
            cy.get('#tablaDiscadores_filter > label > input').clear().type('Auto')
            cy.get('.sorting_1').contains('Power').click()
            cy.get('#eliminar').click()
            cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
        cy.get('#navigation > .menu > li:nth-child(2)').click()
        cy.get('#campaigns').click()
        cy.wait(6000)
            cy.get('#tablaCampanas_filter > label > input').clear()
            cy.get('#tablaCampanas_filter > label > input').type('Auto')
            cy.get('.dataTables_empty')
        cy.get('#dropUsers').click({force: true})
        cy.get('#agents').click({force: true})
        cy.wait(6000)
            cy.get('#basicDataTable_filter > label > input').type('AutomationAgent')
            cy.get('.sorting_1').click()
            cy.get('.btn-danger').click()
            cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-success').click()
            cy.wait(3000)
        cy.get('#btnLogOut').click()
    })

})